#!/bin/bash
# =============================================================================
# Observium Docker Entrypoint Script
# Handles: DB wait → config generation → schema init → admin user → cron → Apache
# =============================================================================

set -o pipefail
set -e

# ---------------------------------------------------------------------------
# Color output helpers
# ---------------------------------------------------------------------------
log_info()  { echo -e "\033[1;32m[INFO]\033[0m  $*"; }
log_warn()  { echo -e "\033[1;33m[WARN]\033[0m  $*"; }
log_error() { echo -e "\033[1;31m[ERROR]\033[0m $*"; }

# ---------------------------------------------------------------------------
# 0. Validate required environment variables
# ---------------------------------------------------------------------------
log_info "Validating environment variables..."
required_vars="DB_HOST DB_USER DB_PASSWORD DB_NAME OBSERVIUM_ADMIN_USER OBSERVIUM_ADMIN_PASSWORD"
for var in $required_vars; do
    value="${!var}"
    if [ -z "$value" ]; then
        log_error "Required environment variable $var is not set!"
        exit 1
    fi
done
log_info "All required variables are set."

# ---------------------------------------------------------------------------
# 1. Set timezone
# ---------------------------------------------------------------------------
if [ -n "$TZ" ]; then
    ln -snf /usr/share/zoneinfo/"$TZ" /etc/localtime
    echo "$TZ" > /etc/timezone
    log_info "Timezone set to: $TZ"
fi

# ---------------------------------------------------------------------------
# 2. Wait for MariaDB to be ready
# ---------------------------------------------------------------------------
DB_CONNECTION_TIMEOUT=${DB_CONNECTION_TIMEOUT:-90}
export MYSQL_PWD="${DB_PASSWORD}"

log_info "Waiting for MariaDB at '${DB_HOST}' (timeout: ${DB_CONNECTION_TIMEOUT}s)..."
attempt=0
while [ $attempt -lt $DB_CONNECTION_TIMEOUT ]; do
    attempt=$((attempt + 1))
    if mariadb --user="${DB_USER}" -h "${DB_HOST}" -D "${DB_NAME}" -e "SELECT 1" > /dev/null 2>&1; then
        log_info "Successfully connected to MariaDB! (attempt ${attempt})"
        break
    fi
    if [ $attempt -eq $DB_CONNECTION_TIMEOUT ]; then
        log_error "Failed to connect to MariaDB after ${DB_CONNECTION_TIMEOUT} attempts. Exiting."
        exit 1
    fi
    sleep 1
done

# ---------------------------------------------------------------------------
# 3. Generate config.php
# ---------------------------------------------------------------------------
CONFIG_FILE="/opt/observium/config.php"

log_info "Generating Observium config.php..."
cat > "$CONFIG_FILE" <<EOPHP
<?php

// =============================================================================
// Observium Configuration - Auto-generated by Docker entrypoint
// Generated at: $(date '+%Y-%m-%d %H:%M:%S %Z')
// =============================================================================

// Database configuration
\$config['db_host']     = '${DB_HOST}';
\$config['db_name']     = '${DB_NAME}';
\$config['db_user']     = '${DB_USER}';
\$config['db_pass']     = '${DB_PASSWORD}';

// Directories
\$config['rrd_dir']     = '/opt/observium/rrd';
\$config['log_dir']     = '/opt/observium/logs';
\$config['install_dir'] = '/opt/observium';

// fping location
\$config['fping']       = '/usr/bin/fping';
\$config['fping6']      = '/usr/bin/fping6';

// Default SNMP community
\$config['snmp']['community'][] = '${OBSERVIUM_SNMP_COMMUNITY:-public}';

// Web interface
\$config['base_url']    = 'http://localhost:8080';

// Housekeeping settings
\$config['housekeeping']['deleted_ports']['age'] = 86400;

EOPHP

# Append any extra OBSERVIUM__ environment variables to config.php
# Format: OBSERVIUM__key1__key2=value -> $config['key1']['key2'] = value;
env | (grep '^OBSERVIUM__' || true) | while IFS='=' read -r key value; do
    # Skip known non-config variables
    case "$key" in
        OBSERVIUM_ADMIN_USER|OBSERVIUM_ADMIN_PASSWORD|OBSERVIUM_SNMP_COMMUNITY|OBSERVIUM_PORT|OBSERVIUM_FQDN)
            continue
            ;;
    esac

    # Remove OBSERVIUM__ prefix
    php_key="${key#OBSERVIUM__}"

    # Convert __ to ']['  and ___ to - for PHP array notation
    # First handle triple underscore (becomes hyphen in key name)
    php_key="${php_key//___/-}"
    # Then handle double underscore (becomes array separator)
    php_key=$(echo "$php_key" | sed "s/__/']['/g")

    # Type conversion
    case "$value" in
        true|TRUE)   php_value="TRUE" ;;
        false|FALSE) php_value="FALSE" ;;
        ''|*[!0-9]*) php_value="'$value'" ;;  # String (non-numeric)
        0*)          php_value="'$value'" ;;   # String with leading zero
        *)           php_value="$value" ;;     # Integer
    esac

    echo "\$config['${php_key}'] = ${php_value};" >> "$CONFIG_FILE"
done

# Close PHP tag is intentionally omitted (PHP best practice)
log_info "config.php generated successfully."

# ---------------------------------------------------------------------------
# 4. Initialize database schema if needed
# ---------------------------------------------------------------------------
table_count=$(mariadb --user="${DB_USER}" -h "${DB_HOST}" -D "${DB_NAME}" -N -B -e \
    "SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA='${DB_NAME}'" 2>/dev/null || echo "0")

if [ "$table_count" -eq 0 ]; then
    log_info "Database is empty. Initializing Observium schema..."
    cd /opt/observium
    php discovery.php -u
    log_info "Database schema initialized successfully."
else
    log_info "Database already initialized (${table_count} tables found). Running schema update..."
    cd /opt/observium
    php discovery.php -u
    log_info "Schema update complete."
fi

# ---------------------------------------------------------------------------
# 5. Create admin user if not exists
# ---------------------------------------------------------------------------
admin_exists=$(mariadb --user="${DB_USER}" -h "${DB_HOST}" -D "${DB_NAME}" -N -B -e \
    "SELECT COUNT(*) FROM users WHERE username='${OBSERVIUM_ADMIN_USER}'" 2>/dev/null || echo "0")

if [ "$admin_exists" -eq 0 ]; then
    log_info "Creating admin user '${OBSERVIUM_ADMIN_USER}'..."
    cd /opt/observium
    php adduser.php "${OBSERVIUM_ADMIN_USER}" "${OBSERVIUM_ADMIN_PASSWORD}" 10
    log_info "Admin user created successfully."
else
    log_info "Admin user '${OBSERVIUM_ADMIN_USER}' already exists. Skipping."
fi

# ---------------------------------------------------------------------------
# 6. Set directory permissions
# ---------------------------------------------------------------------------
log_info "Setting directory permissions..."
chown -R www-data:www-data /opt/observium/rrd
chown -R www-data:www-data /opt/observium/logs
chmod 775 /opt/observium/rrd
chmod 775 /opt/observium/logs

# ---------------------------------------------------------------------------
# 7. Setup cron jobs for discovery & polling
# ---------------------------------------------------------------------------
log_info "Setting up cron jobs..."

# INJECTION: Force Observium to load the custom Raisecom script during discovery
DISCOVERY_CORE="/opt/observium/discovery.php"
CUSTOM_SCRIPT="/opt/observium/includes/discovery/sensors/raisecom-optical-transceiver-mib.inc.php"

if [ -f "$DISCOVERY_CORE" ]; then
    if ! grep -q "raisecom-optical-transceiver-mib.inc.php" "$DISCOVERY_CORE"; then
        log_info "Injecting custom Raisecom script into discovery.php..."
        echo "" >> "$DISCOVERY_CORE"
        echo "/* CUSTOM RAISECOM SCRIPT INJECTION */" >> "$DISCOVERY_CORE"
        echo "if (isset(\$device) && \$device['os'] == 'raisecom-ipn' && file_exists('$CUSTOM_SCRIPT')) { include('$CUSTOM_SCRIPT'); }" >> "$DISCOVERY_CORE"
    fi
fi

CRON_FILE="/etc/cron.d/observium"
cat > "$CRON_FILE" <<'EOCRON'
# Observium cron jobs
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Discovery of all devices - every 6 hours
33 */6 * * * www-data /opt/observium/observium-wrapper discovery >> /opt/observium/logs/discovery-cron.log 2>&1

# Discovery of newly added devices - every 5 minutes
*/5 * * * * www-data /opt/observium/observium-wrapper discovery --host new >> /opt/observium/logs/discovery-new-cron.log 2>&1

# Polling of all devices - every 5 minutes
*/5 * * * * www-data /opt/observium/observium-wrapper poller >> /opt/observium/logs/poller-cron.log 2>&1

# Housekeeping - daily at 03:13
13 3 * * * www-data /opt/observium/housekeeping.php -ysel >> /opt/observium/logs/housekeeping-cron.log 2>&1
EOCRON

chmod 644 "$CRON_FILE"
log_info "Cron jobs configured."

# ---------------------------------------------------------------------------
# 8. Start services
# ---------------------------------------------------------------------------
log_info "Starting cron daemon..."
service cron start

log_info "=============================================="
log_info "  Observium is ready!"
log_info "  Version: $(cat /opt/observium/VERSION 2>/dev/null || echo 'unknown')"
log_info "  Admin:   ${OBSERVIUM_ADMIN_USER}"
log_info "  URL:     http://localhost:8080"
log_info "=============================================="

# Start Apache in foreground (PID 1)
log_info "Starting Apache in foreground..."
exec apachectl -D FOREGROUND
